# Generated by Django 2.0.8 on 2018-08-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(max_length=200, upload_to='org/%Y/%m', verbose_name='封面'),
        ),
    ]
