# Generated by Django 2.0.8 on 2018-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180831_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', max_length=200, upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
