# Generated by Django 2.0.8 on 2018-09-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='全国知名', max_length=50, verbose_name='机构标签'),
        ),
    ]
