# Generated by Django 2.0.8 on 2018-09-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180904_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='courses/%Y/%m', verbose_name='封面'),
        ),
    ]
